USE_GEMINI = false

GPT_BASE = "address of you deployment of Chat GPT"
GPT_VERSION = "version date"
GPT_KEY = "your key"
GPT_CHAT_MODEL = "chat model"
GPT_EMBEDDINGS_MODEL = "embedding model"

GEMINI_API_KEY = "KEY HERE"
GEMINI_CHAT_MODEL = "gemini model"
GEMINI_EMBEDDING_MODEL = "gemini embeddings model"

USE_LM_STUDIO = false
LM_STUDIO_EMBEDDING_MODEL= "embeddings model"
# Copy the "Reachable at" address from LM Studio's local server page and append /v1
LM_STUDIO_API_BASE = "http://...../v1"
LM_STUDIO_API_KEY= "lmstudio"
LM_STUDIO_CHAT_MODEL = "llm model"