USE_GEMINI = false

GPT_BASE = "address of you deployment of Chat GPT"
GPT_VERSION = "version date"
GPT_KEY = "your key"
GPT_CHAT_MODEL = "chat model"
GPT_EMBEDDINGS_MODEL = "embedding model"

GEMINI_API_KEY = "KEY HERE"
GEMINI_CHAT_MODEL = "gemini model"
GEMINI_EMBEDDING_MODEL = "gemini embeddings model"
